#  application-dev.yml文件内容=============================================================================
# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xkqq.top:3306/db_aurain?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: "root"
      password: "012151"
  # Redis的相关配置
  data:
    redis:
      host: "xkqq.top"
      port: 6379
      password: "012151"

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

aurain:
  auth:
    no-auth-urls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /test
      - /swagger/**
      - /swagger-resources/**
      - /v3/**
      - /webjars/**
      - /doc.html
      - swagger-ui.html
